### ISSUE TITLE
Non-clickable Icons

### ISSUE THREAD

**Issue by tristinDLC** [Porco-Rosso/Ubersicht-Nightshades#1]
Love the widget as I use my computer wallpaper as a nightlight of sorts for my GF. At it's lowest setting, it's still bright, but with Nightshades it has been way easier on the eyes. Anyway, none of the icons/buttons are clickable to ever change settings. As of right now, I have to manually move the midget folder in and out of the Ubersicht folder to turn the widget on and off. 

Currently running macOS 10.12.4

It's getting to be inconvenient to manually move the folder on top of actually adjusting my monitor brightness each time I want to sleep or get to work. Would be nice to get clickable buttons to work as advertised. Thanks!

**Comment by tristinDLC** [comment]
I was actually able to resolve my own issue as it was an Ubersicht setting I was not aware of. I ended up having the same problem with a second app, so I knew it had to be something more universal.

For anyone having issues being able to click or interact with their widgets, you must enable Interactions via the Ubersicht Preference menu. It would be nice if it was enabled via default as a lot of widgets that have interactability do not mention that preference setting being a prerequisite.

Anyway, wanted to update my situation so that others may hopefully benefit.

**Comment by Porco-Rosso** [comment]
Glad to hear you resolved the issue. I've added a note to the readme.
