### ISSUE TITLE
Default setting

### ISSUE THREAD

**Issue by SheaHolden** [Porco-Rosso/Ubersicht-Nightshades#2]
Is there a way to set the default setting when Nightshades is started? By that I don't mean the shade level, I mean whether it is displayed or not (ie: I want the shades to be OFF on startup, as it is they are on by default)

**Comment by Porco-Rosso** [comment]
Hi, I see you closed the issue, so I assume you figured it out. But for anyone looking for a solution, just change `index.coffee` to:
```   
      <th><span class="level">.3</span></th>
      <th><span class="level selected">.5</span></th>
      <th><span class="level">.8</span></th>

```

to
```
      <th><span class="level">.3</span></th>
      <th><span class="level">.5</span></th>
      <th><span class="level">.8</span></th>
```
